export const PROCESSING_STATUSES = Object.freeze({
  UNPROCESSED: "UNPROCESSED",
  PROCESSING: "PROCESSING",
  RELEVANT: "RELEVANT",
  IRRELEVANT: "IRRELEVANT",
  NEEDS_REVIEW: "NEEDS_REVIEW",
  PROCESSING_ERROR: "PROCESSING_ERROR",
});

export const CURRENT_CONFIRMED = "CURRENTLY_CONFIRMED";
export const POTENTIALLY_AFFECTED = "POTENTIALLY_AFFECTED";

export const DEFAULT_PAGE_SIZE = 25;
export const MAX_PAGE_SIZE = 100;
